http://localhost:3000/player/new/Pedro
###
http://localhost:3000/player/new/Carina
###
http://localhost:3000/player/new/Jose
###
http://localhost:3000/player/new/Sofia
###

http://localhost:3000/group/new/CRU
###

http://localhost:3000/player/player1/join/group/group5
###
http://localhost:3000/player/player2/join/group/group5
###
http://localhost:3000/player/player1/join/group/group5
###
http://localhost:3000/player/player1/leave/group/group5
###
